./src/params.vh
./src/bus_arbiter.v
./src/cache/cacheblock/sky130_sram_1kbyte_1rw1r_32x256_8.v
./src/cache/cacheblock/sky130_sram_1rw1r_64x256_8.v
./src/cache/cacheblock/std_dffe.v
./src/cache/cacheblock/std_dffr.v
./src/cache/l1dcache.v
./src/cache/l1icache_32.v
./src/core_empty/core_empty.v
./src/core_empty/lsu/ac.v
./src/core_empty/lsu/agu.v
./src/core_empty/lsu/cu.v
./src/core_empty/lsu/lr.v
./src/core_empty/lsu/lsq.v
./src/core_empty/lsu/nblsu.v
./src/core_empty/mmu/leaf_pte_check.v
./src/core_empty/mmu/mmu_sv39.v
./src/core_empty/mmu/ptw.v
./src/core_empty/pipeline/backend.v
./src/core_empty/pipeline/frontend.v
./src/core_empty/units/btb.v
./src/core_empty/units/counter.v
./src/core_empty/units/counter_rob.v
./src/core_empty/units/counter_tmp.v
./src/core_empty/units/csr.v
./src/core_empty/units/decode.v
./src/core_empty/units/excep_ctrl.v
./src/core_empty/units/fake_icache.v
./src/core_empty/units/fetch.v
./src/core_empty/units/fifo.v
./src/core_empty/units/fifo_tmp.v
./src/core_empty/units/gshare.v
./src/core_empty/units/ins_buffer.v
./src/core_empty/units/new_alu.v
./src/core_empty/units/new_fu.v
./src/core_empty/units/physical_regfile.v
./src/core_empty/units/rcu.v
./src/hehe.v
./src/macros/verilog/sky130_sram_1kbyte_1rw1r_32x256_8.v

../../dv/hehe_tb.sv 
../../dv/dpram64.v